ezplatform_page_fieldtype:
    layouts:
        sidebar:
            identifier: sidebar
            name: Right sidebar
            description: Main section with sidebar on the right
            thumbnail: /assets/images/layouts/sidebar.png
            template: layouts/sidebar.html.twig
            zones:
                first:
                    name: First zone
                second:
                    name: Second zone
    blocks:
        contentlist:
            views:
                contentList:
                    template: blocks/contentlist/default.html.twig
                    name: Content List
        schedule:
            views:
                featured:
                    template: blocks/schedule/featured.html.twig
                    name: Featured Schedule Block
