ezplatform_page_fieldtype:
    layouts:
        sidebar:
            identifier: sidebar
            name: Right sidebar
            description: Main section with sidebar on the right
            thumbnail: assets/images/layouts/sidebar.png
            template: layouts/sidebar.html.twig
            zones:
                first:
                    name: First zone
                second:
                    name: Second zone
    blocks:
        contentlist:
            views:
                contentList:
                    template: blocks/contentlist.html.twig
                    name: Content List
#       This block is not supported by PageBuilder in v2.2
#        schedule:
#            views:
#                sqchedule_featured:
#                    template: blocks/schedule_featured.html.twig
#                    name: Featured Schedule Block
#                schedule_list:
#                    template: blocks/schedule_list.html.twig
#                    name: List Schedule Block
