services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.controller.menu:
        class: AppBundle\Controller\MenuController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@ezpublish.query_type.registry'
        public: true
            
    AppBundle\Block\Event\Listener\RandomBlockListener: ~

    app.block.random.converter:
        class: EzSystems\EzPlatformPageMigration\Converter\AttributeConverter\DefaultConverter
        tags:
            - { name: ezplatform.fieldtype.ezlandingpage.migration.attribute.converter, block_type: random }
